export { default as Navbar } from "./NavBar";
export { default as Home } from "./Home";
export { default as Students } from "./Students";
export { default as Degrees } from "./Degrees";
export { default as Courses } from "./Courses";
export { default as Trends } from "./Trends";
export { default as AddStudent } from "./AddStudent";
export { default as InvalidLogin } from "./InvalidLogin";
// export { default as EditStudentAsAdvisor } from "./EditStudentAsAdvisor";
export { default as EditStudent } from "./EditStudent";
export { default as BarChar } from "./BarChart";